global using AutoMapper;
global using Caisy.Web;
global using Caisy.Web.Features.Settings;
global using Caisy.Web.Features.Shared;
global using Caisy.Web.Features.Shared.Handlers;
global using Caisy.Web.Features.Shared.Services;
global using Caisy.Web.Features.Shared.Utilities;
global using Caisy.Web.Infrastructure;
global using Caisy.Web.Infrastructure.Models;
global using Caisy.Web.Shared;
global using MediatR;
global using Microsoft.AspNetCore.Components;
global using MudBlazor;
global using Message = Caisy.Web.Features.Shared.ConversationBase.Message;
